### ISSUE TITLE
hdblog.it

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoDefender#37] opened 2018-04-10 08:51 UTC
not work on hdblog.it
example: https://huawei.hdblog.it/2018/04/09/huawei-p20-test-live-batteria/

**Comment by jspenguin2017** [comment] 2018-04-10 14:10
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/904

**Closed by jspenguin2017** 2018-04-10 14:10 UTC
