### ISSUE TITLE
not work on italiashare.net

### ISSUE THREAD

**Issue by gabri25ele** [NanoAdblocker/NanoDefender#17] opened 2018-01-25 15:48 UTC
on italiashare.net defender not work anymore :(
any idea to fix it?

**Comment by jspenguin2017** [comment] 2018-01-25 16:02
Ops, I totally forgot to fix it... 
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/126

**Comment by jspenguin2017** [comment] 2018-01-25 16:03
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/126

**Closed** 2018-01-25 16:02 UTC
Labels: duplicate
