### ISSUE TITLE
trustedreviews.com

### ISSUE THREAD

**Issue by skanskan** [NanoAdblocker/NanoDefender#27] opened 2018-02-24 21:06 UTC
Hello

Some web sites don't work. They start loading but at the end refuse to continue loading and casta an error saying maybe it's caused by an adblock.
For example this well-known site:

### Test link (required): 
http://www.trustedreviews.com/news/sony-xperia-xz-pro-release-date-price-design-specs-leak-3373728

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/NKSuSxn.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/JdeuqJI.png

### Environment (Required): 

Windows 10 X64
Chrome  63.0.3239.132 (Official Build) (64-bit)
uBlock Origin v1.15.2
Nano Defender 13.36

#### Your filter lists (Required): 

Ru Adlist
EasyList Spanish
Peter Lowe’s Ad and tracking server list
Fanboy’s Annoyance List
Malware domains and list
EasyPrivacy
Easylist
Adblock Warning Removal List
uBlock filters

**Comment by jspenguin2017** [comment] 2018-02-24 21:55
I can't reproduce the block screen but I see a few ads around.

**Comment by jspenguin2017** [comment] 2018-02-25 17:47
Resolved in uAssets: 
https://github.com/uBlockOrigin/uAssets/issues/1617

**Closed by jspenguin2017** 2018-02-25 17:47 UTC
Labels: fixed
